name: 'Contributors action'
description: 'Create contributors markdown file'
inputs:
  path:
    description: 'Path of contributors file'
    required: true
    default: 'contributors.json'
  template_path:
    description: 'Path of template file'
    required: true
    default: 'templates/basic.liquid'
  output_path:
    description: 'Path of contributors generated file'
    required: true
    default: 'contributors.md'
runs:
  using: 'node12'
  main: './dist/index.js'
