on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to add contributors markdown
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate markdown file
        uses: ./
